export const OREDER_CREATE_REQUEST = 'OREDER_CREATE_REQUEST'
export const OREDER_CREATE_SUCCESS = 'OREDER_CREATE_SUCCESS'
export const OREDER_CREATE_FAIL = 'OREDER_CREATE_FAIL'
export const OREDER_CREATE_RESET = 'OREDER_CREATE_RESET'

export const OREDER_DETAILS_REQUEST = 'OREDER_DETAILS_REQUEST'
export const OREDER_DETAILS_SUCCESS = 'OREDER_DETAILS_SUCCESS'
export const OREDER_DETAILS_FAIL = 'OREDER_DETAILS_FAIL'
export const OREDER_DETAILS_REST = 'OREDER_DETAILS_RESET'

export const OREDER_PAY_REQUEST = 'OREDER_PAY_REQUEST'
export const OREDER_PAY_SUCCESS = 'OREDER_PAY_SUCCESS'
export const OREDER_PAY_FAIL = 'OREDER_PAY_FAIL'
export const OREDER_PAY_RESET = 'OREDER_PAY_RESET'

export const OREDER_LIST_MY_REQUEST = 'OREDER_LIST_MY_REQUEST'
export const OREDER_LIST_MY_SUCCESS = 'OREDER_LIST_MY_SUCCESS'
export const OREDER_LIST_MY_FAIL = 'OREDER_LIST_MY_FAIL'
export const OREDER_LIST_MY_RESET = 'OREDER_LIST_MY_RESET'


export const OREDER_LIST_REQUEST = 'OREDER_LIST_REQUEST'
export const OREDER_LIST_SUCCESS = 'OREDER_LIST_SUCCESS'
export const OREDER_LIST_FAIL = 'OREDER_LIST_FAIL'
export const OREDER_LIST_RESET = 'OREDER_LIST_RESET'


export const OREDER_DELIVERED_REQUEST = 'OREDER_DELIVERED_REQUEST'
export const OREDER_DELIVERED_SUCCESS = 'OREDER_DELIVERED_SUCCESS'
export const OREDER_DELIVERED_FAIL = 'OREDER_DELIVERED_FAIL'
export const OREDER_DELIVERED_RESET = 'OREDER_DELIVERED_RESET'